test:
  workers:
    type: local
    number: 1
  rounds:
    - label: Create Sensor Data 1
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 30
      workload:
        module: benchmarks/scenario/simple/pavan-v2.2/createIOTData.js
    # - label: Create Sensor Data 2
    #   txNumber: 200
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 20
    #   workload:
    #       module: benchmarks/scenario/simple/pavan-v2.2/createIOTData.js
    - label: Create Patient Data 
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
          module: benchmarks/scenario/simple/pavan-v2.2/createPatient.js
    - label: Get Patient Data 
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 150
      workload:
          module: benchmarks/scenario/simple/pavan-v2.2/queryPatient.js

    # - label: Create Car 2
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
    # - label: Create Car 3
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
    # - label: Create Car 4
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
    # - label: Create Car 5
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
    # - label: Create Car 6
    #   txNumber: 600
    #   rateControl:
    #     type: fixed-rate
    #     opts:
    #       tps: 150
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js