name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric

info:
  Version: 2.1.0
  Size: 5 Orgs with 1 Peer
  Orderer: Raft
  Distribution: Single Host
  StateDB: CouchDB

clients:
  client0.org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem

  client0.org2.example.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/cert.pem
  
  client0.org3.example.com:
    client:
      organization: Org3
      credentialStore:
        path: /tmp/hfc-kvs/org3
        cryptoStore:
          path: /tmp/hfc-cvs/org3
      clientPrivateKey:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/keystore/priv_sk
      clientSignedCert:
        path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/signcerts/cert.pem
  
  # client0.org4.example.com:
  #   client:
  #     organization: Org4
  #     credentialStore:
  #       path: /tmp/hfc-kvs/org4
  #       cryptoStore:
  #         path: /tmp/hfc-cvs/org4
  #     clientPrivateKey:
  #       path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/keystore/priv_sk
  #     clientSignedCert:
  #       path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/signcerts/cert.pem

  # client0.org5.example.com:
  #   client:
  #     organization: Org5
  #     credentialStore:
  #       path: /tmp/hfc-kvs/org5
  #       cryptoStore:
  #         path: /tmp/hfc-cvs/org5
  #     clientPrivateKey:
  #       path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org5.example.com/users/User1@org5.example.com/msp/keystore/priv_sk
  #     clientSignedCert:
  #       path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org5.example.com/users/User1@org5.example.com/msp/signcerts/cert.pem

channels:
  mychannel:
    # configBinary: networks/fabric/pavan-v2.1/mychannel.tx
    created: true
    contracts: [{ "id": "fabcar", "version": "1" }]
    definition:
      capabilities: []
      consortium: "SampleConsortium"
      msps: ["Org1MSP", "Org2MSP", "Org3MSP"]
      version: 0
    orderers:
      - orderer.example.com
      - orderer2.example.com
      - orderer3.example.com
    peers:
      peer0.org1.example.com:
        eventSource: true
      peer0.org2.example.com:
        eventSource: true
      peer0.org3.example.com:
        eventSource: true
      # peer0.org4.example.com:
      #   eventSource: true
      # peer0.org5.example.com:
      #   eventSource: true

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com
    adminPrivateKey:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem

  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.example.com
    certificateAuthorities:
      - ca.org2.example.com
    adminPrivateKey:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/cert.pem

  Org3:
    mspid: Org3MSP
    peers:
      - peer0.org3.example.com
    certificateAuthorities:
      - ca.org3.example.com
    adminPrivateKey:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp/keystore/priv_sk
    signedCert:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp/signcerts/cert.pem

  # Org4:
  #   mspid: Org4MSP
  #   peers:
  #     - peer0.org4.example.com
  #   certificateAuthorities:
  #     - ca.org4.example.com
  #   adminPrivateKey:
  #     path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp/keystore/priv_sk
  #   signedCert:
  #     path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp/signcerts/cert.pem

  # Org5:
  #   mspid: Org5MSP
  #   peers:
  #     - peer0.org5.example.com
  #   certificateAuthorities:
  #     - ca.org5.example.com
  #   adminPrivateKey:
  #     path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org5.example.com/users/Admin@org5.example.com/msp/keystore/priv_sk
  #   signedCert:
  #     path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org5.example.com/users/Admin@org5.example.com/msp/signcerts/cert.pem

orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  orderer2.example.com:
    url: grpcs://localhost:8050
    grpcOptions:
      ssl-target-name-override: orderer2.example.com
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  orderer3.example.com:
    url: grpcs://localhost:9050
    grpcOptions:
      ssl-target-name-override: orderer3.example.com
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/tlscacerts/tls-localhost-7054-ca-org1-example-com.pem

  peer0.org2.example.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/tlscacerts/tls-localhost-8054-ca-org2-example-com.pem
  
  peer0.org3.example.com:
    url: grpcs://localhost:11051
    grpcOptions:
      ssl-target-name-override: peer0.org3.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/tlscacerts/tls-localhost-10054-ca-org3-example-com.pem

  # peer0.org4.example.com:
  #   url: grpcs://localhost:12051
  #   grpcOptions:
  #     ssl-target-name-override: peer0.org4.example.com
  #     grpc.keepalive_time_ms: 600000
  #   tlsCACerts:
  #     path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls/tlscacerts/tls-localhost-11054-ca-org4-example-com.pem

  # peer0.org5.example.com:
  #   url: grpcs://localhost:13051
  #   grpcOptions:
  #     ssl-target-name-override: peer0.org5.example.com
  #     grpc.keepalive_time_ms: 600000
  #   tlsCACerts:
  #     path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org5.example.com/peers/peer0.org5.example.com/tls/tlscacerts/tls-localhost-12054-ca-org5-example-com.pem

certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

  ca.org2.example.com:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

  ca.org3.example.com:
    url: https://localhost:10054
    httpOptions:
      verify: false
    tlsCACerts:
      path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org3.example.com/tlsca/tlsca.org3.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

  # ca.org4.example.com:
  #   url: https://localhost:11054
  #   httpOptions:
  #     verify: false
  #   tlsCACerts:
  #     path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org4.example.com/tlsca/tlsca.org4.example.com-cert.pem
  #   registrar:
  #     - enrollId: admin
  #       enrollSecret: adminpw

  # ca.org5.example.com:
  #   url: https://localhost:12054
  #   httpOptions:
  #     verify: false
  #   tlsCACerts:
  #     path: networks/fabric/pavan-v2.1/crypto-config/peerOrganizations/org5.example.com/tlsca/tlsca.org5.example.com-cert.pem
  #   registrar:
  #     - enrollId: admin
  #       enrollSecret: adminpw
